import { ALLOW_MOCK_FALLBACK } from "@/shared/config/platform";
import { apiClient, ApiError, platformPath } from "@/shared/api/client";
import type { DatabasesSnapshot } from "./types";

function mockSnapshot(): DatabasesSnapshot {
  const h = ["00", "04", "08", "12", "16", "20"];
  return {
    generatedAt: new Date().toISOString(),
    kpis: {
      clusters: 14,
      unhealthy: 2,
      backups24h: 38,
      avgLagMs: 42,
      migrationsActive: 1,
      storagePct: 68,
    },
    qpsSeries: h.map((label, i) => ({
      label: `${label}:00`,
      value: 8200 + i * 1400 + (i % 2) * 600,
    })),
    lagSeries: h.map((label, i) => ({
      label: `${label}:00`,
      value: 18 + i * 8 + (i === 4 ? 40 : 0),
    })),
    clusters: [
      {
        id: "db1",
        name: "pg-platform-eu",
        engine: "postgres",
        version: "16.3",
        region: "eu-west-1",
        role: "primary",
        status: "healthy",
        connections: 412,
        maxConnections: 800,
        storageUsedPct: 61,
        lagMs: null,
        qps: 4200,
      },
      {
        id: "db2",
        name: "pg-platform-eu-r1",
        engine: "postgres",
        version: "16.3",
        region: "eu-west-1",
        role: "replica",
        status: "healthy",
        connections: 180,
        maxConnections: 800,
        storageUsedPct: 61,
        lagMs: 28,
        qps: 2100,
      },
      {
        id: "db3",
        name: "redis-session",
        engine: "redis",
        version: "7.2",
        region: "eu-west-1",
        role: "cluster",
        status: "healthy",
        connections: 2400,
        maxConnections: 10000,
        storageUsedPct: 44,
        lagMs: 2,
        qps: 98000,
      },
      {
        id: "db4",
        name: "os-search-global",
        engine: "opensearch",
        version: "2.15",
        region: "multi",
        role: "cluster",
        status: "degraded",
        connections: 96,
        maxConnections: 500,
        storageUsedPct: 78,
        lagMs: null,
        qps: 6400,
      },
      {
        id: "db5",
        name: "ch-analytics",
        engine: "clickhouse",
        version: "24.8",
        region: "eu-central-1",
        role: "cluster",
        status: "healthy",
        connections: 64,
        maxConnections: 200,
        storageUsedPct: 72,
        lagMs: null,
        qps: 1800,
      },
      {
        id: "db6",
        name: "pg-tenant-ent-a",
        engine: "postgres",
        version: "15.8",
        region: "us-east-1",
        role: "primary",
        status: "failover",
        connections: 220,
        maxConnections: 500,
        storageUsedPct: 55,
        lagMs: null,
        qps: 900,
      },
    ],
    backups: [
      {
        id: "bk1",
        clusterId: "db1",
        clusterName: "pg-platform-eu",
        engine: "postgres",
        type: "full",
        sizeGb: 820,
        status: "completed",
        startedAt: new Date(Date.now() - 6 * 3600000).toISOString(),
        finishedAt: new Date(Date.now() - 5.2 * 3600000).toISOString(),
        retentionDays: 30,
      },
      {
        id: "bk2",
        clusterId: "db5",
        clusterName: "ch-analytics",
        engine: "clickhouse",
        type: "incremental",
        sizeGb: 140,
        status: "completed",
        startedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
        finishedAt: new Date(Date.now() - 1.7 * 3600000).toISOString(),
        retentionDays: 14,
      },
      {
        id: "bk3",
        clusterId: "db3",
        clusterName: "redis-session",
        engine: "redis",
        type: "snapshot",
        sizeGb: 48,
        status: "running",
        startedAt: new Date(Date.now() - 12 * 60000).toISOString(),
        finishedAt: null,
        retentionDays: 7,
      },
      {
        id: "bk4",
        clusterId: "db4",
        clusterName: "os-search-global",
        engine: "opensearch",
        type: "snapshot",
        sizeGb: 2100,
        status: "failed",
        startedAt: new Date(Date.now() - 9 * 3600000).toISOString(),
        finishedAt: new Date(Date.now() - 8.5 * 3600000).toISOString(),
        retentionDays: 21,
      },
    ],
    replication: [
      {
        id: "rep1",
        source: "pg-platform-eu",
        target: "pg-platform-eu-r1",
        engine: "postgres",
        lagMs: 28,
        status: "streaming",
        mode: "async",
      },
      {
        id: "rep2",
        source: "pg-platform-eu",
        target: "pg-platform-dr-warm",
        engine: "postgres",
        lagMs: 420,
        status: "catching_up",
        mode: "async",
      },
      {
        id: "rep3",
        source: "redis-session",
        target: "redis-session-replica",
        engine: "redis",
        lagMs: 2,
        status: "streaming",
        mode: "async",
      },
      {
        id: "rep4",
        source: "ch-analytics-shard0",
        target: "ch-analytics-shard0-r",
        engine: "clickhouse",
        lagMs: 0,
        status: "streaming",
        mode: "sync",
      },
    ],
    failovers: [
      {
        id: "fo1",
        clusterName: "pg-tenant-ent-a",
        engine: "postgres",
        fromNode: "ent-a-primary",
        toNode: "ent-a-standby",
        reason: "Primary disk I/O saturation",
        status: "in_progress",
        at: new Date(Date.now() - 18 * 60000).toISOString(),
        dualControl: true,
      },
      {
        id: "fo2",
        clusterName: "redis-cache-apac",
        engine: "redis",
        fromNode: "apac-m1",
        toNode: "apac-m2",
        reason: "AZ outage",
        status: "completed",
        at: new Date(Date.now() - 2 * 86400000).toISOString(),
        dualControl: true,
      },
    ],
    migrations: [
      {
        id: "mig1",
        name: "pg-platform → 16.4",
        engine: "postgres",
        fromVersion: "16.3",
        toVersion: "16.4",
        progressPct: 34,
        status: "running",
        startedAt: new Date(Date.now() - 3 * 3600000).toISOString(),
      },
      {
        id: "mig2",
        name: "opensearch index remap",
        engine: "opensearch",
        fromVersion: "2.14",
        toVersion: "2.15",
        progressPct: 100,
        status: "completed",
        startedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
      },
      {
        id: "mig3",
        name: "clickhouse TTL rewrite",
        engine: "clickhouse",
        fromVersion: "24.3",
        toVersion: "24.8",
        progressPct: 0,
        status: "pending",
        startedAt: null,
      },
    ],
  };
}

export async function fetchDatabasesSnapshot(): Promise<DatabasesSnapshot> {
  try {
    return await apiClient<DatabasesSnapshot>(platformPath("/databases"));
  } catch (err) {
    if (!ALLOW_MOCK_FALLBACK) throw err;
    if (err instanceof ApiError || err instanceof TypeError) {
      await new Promise((r) => setTimeout(r, 200));
      return mockSnapshot();
    }
    throw err;
  }
}
