services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: nexora
      POSTGRES_PASSWORD: nexora
      POSTGRES_DB: dispatch
    ports:
      - "5447:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexora -d dispatch"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6386:6379"

  dispatch-service:
    build: .
    ports:
      - "8096:8096"
    environment:
      HTTP_ADDR: ":8096"
      GRPC_ADDR: ":9106"
      CORS_ALLOWED_ORIGINS: "*"
      ROUTING_BASE_URL: "http://host.docker.internal:8097"
      TRACKING_BASE_URL: "http://host.docker.internal:8098"
      GEOFENCE_BASE_URL: "http://host.docker.internal:8099"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
