services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: nexora
      POSTGRES_PASSWORD: nexora
      POSTGRES_DB: payment
    ports:
      - "5440:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexora -d payment"]
      interval: 5s
      timeout: 3s
      retries: 5

  payment-service:
    build: .
    ports:
      - "8089:8089"
    environment:
      HTTP_ADDR: ":8089"
      GRPC_ADDR: ":9099"
      CORS_ALLOWED_ORIGINS: "*"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
