CREATE TABLE IF NOT EXISTS hs_audits (
  id UUID PRIMARY KEY, tenant_id UUID NOT NULL, domain TEXT NOT NULL,
  title TEXT NOT NULL, status TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL,
  completed_at TIMESTAMPTZ NULL
);
CREATE TABLE IF NOT EXISTS hs_findings (
  id UUID PRIMARY KEY, tenant_id UUID NOT NULL, audit_id UUID NOT NULL,
  code TEXT NOT NULL, title TEXT NOT NULL, severity TEXT NOT NULL, status TEXT NOT NULL,
  resolution TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL, resolved_at TIMESTAMPTZ NULL
);
CREATE TABLE IF NOT EXISTS hs_benchmarks (
  id UUID PRIMARY KEY, tenant_id UUID NOT NULL, kind TEXT NOT NULL,
  value DOUBLE PRECISION NOT NULL, target DOUBLE PRECISION NOT NULL, passed BOOLEAN NOT NULL,
  scenario TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS hs_capacity (
  id UUID PRIMARY KEY, tenant_id UUID NOT NULL, key TEXT NOT NULL, name TEXT NOT NULL,
  peak_rps INT NOT NULL, regions TEXT[] NOT NULL DEFAULT '{}', notes TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS hs_chaos (
  id UUID PRIMARY KEY, tenant_id UUID NOT NULL, kind TEXT NOT NULL, name TEXT NOT NULL,
  status TEXT NOT NULL, recovery_sec INT NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL,
  completed_at TIMESTAMPTZ NULL
);
CREATE TABLE IF NOT EXISTS hs_tuning (
  id UUID PRIMARY KEY, tenant_id UUID NOT NULL, key TEXT NOT NULL, layer TEXT NOT NULL,
  uri TEXT NOT NULL, applied BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL,
  applied_at TIMESTAMPTZ NULL, UNIQUE (tenant_id, key)
);
CREATE TABLE IF NOT EXISTS hs_certificates (
  id UUID PRIMARY KEY, tenant_id UUID NOT NULL, version TEXT NOT NULL, status TEXT NOT NULL,
  gates JSONB NOT NULL DEFAULT '{}', issued_at TIMESTAMPTZ NULL, expires_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS hs_outbox (
  id UUID PRIMARY KEY, tenant_id UUID NOT NULL, aggregate_id UUID NOT NULL,
  topic TEXT NOT NULL, key TEXT NOT NULL, payload JSONB NOT NULL, status TEXT NOT NULL,
  attempts INT NOT NULL DEFAULT 0, last_error TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, published_at TIMESTAMPTZ NULL
);
