import { apiClient, ApiError, platformPath } from "@/shared/api/client";
import type { AiPlatformSnapshot } from "./types";

function mockSnapshot(): AiPlatformSnapshot {
  const h = ["00", "04", "08", "12", "16", "20"];
  return {
    generatedAt: new Date().toISOString(),
    kpis: {
      modelsServing: 18,
      trainingJobs: 4,
      inferenceQps: 12400,
      gpuUtilPct: 71,
      tokensPerMin: 8_420_000,
      failedJobs24h: 1,
    },
    inferenceSeries: h.map((label, i) => ({
      label: `${label}:00`,
      value: 6200 + i * 1100 + (i % 2) * 800,
    })),
    gpuUtilSeries: h.map((label, i) => ({
      label: `${label}:00`,
      value: 48 + i * 5 + (i === 3 ? 12 : 0),
    })),
    models: [
      {
        id: "m1",
        name: "rec-v3",
        kind: "recommendation",
        version: "3.4.1",
        framework: "PyTorch",
        status: "serving",
        accuracyPct: 91.2,
        latencyP99Ms: 38,
        requestsPerMin: 42000,
        owner: "ml-recs",
      },
      {
        id: "m2",
        name: "demand-forecast",
        kind: "forecast",
        version: "2.1.0",
        framework: "Prophet+NN",
        status: "serving",
        accuracyPct: 87.4,
        latencyP99Ms: 120,
        requestsPerMin: 1800,
        owner: "ml-forecast",
      },
      {
        id: "m3",
        name: "dynamic-pricing",
        kind: "pricing",
        version: "1.8.2",
        framework: "XGBoost",
        status: "staging",
        accuracyPct: 89.0,
        latencyP99Ms: 22,
        requestsPerMin: 0,
        owner: "ml-pricing",
      },
      {
        id: "m4",
        name: "semantic-search",
        kind: "search",
        version: "4.0.0",
        framework: "sentence-transformers",
        status: "serving",
        accuracyPct: 93.1,
        latencyP99Ms: 55,
        requestsPerMin: 28000,
        owner: "search-ml",
      },
      {
        id: "m5",
        name: "receipt-ocr",
        kind: "ocr",
        version: "1.2.5",
        framework: "PaddleOCR",
        status: "serving",
        accuracyPct: 96.8,
        latencyP99Ms: 210,
        requestsPerMin: 640,
        owner: "ml-vision",
      },
      {
        id: "m6",
        name: "support-chatbot",
        kind: "chatbot",
        version: "0.9.3",
        framework: "vLLM",
        status: "training",
        accuracyPct: null,
        latencyP99Ms: null,
        requestsPerMin: 0,
        owner: "ml-chat",
      },
    ],
    trainingJobs: [
      {
        id: "tj1",
        modelName: "support-chatbot",
        kind: "chatbot",
        status: "running",
        progressPct: 62,
        gpus: 8,
        startedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
        etaMin: 140,
        dataset: "support-transcripts-v12",
      },
      {
        id: "tj2",
        modelName: "dynamic-pricing",
        kind: "pricing",
        status: "queued",
        progressPct: 0,
        gpus: 4,
        startedAt: null,
        etaMin: null,
        dataset: "price-elasticity-q2",
      },
      {
        id: "tj3",
        modelName: "rec-v3.5",
        kind: "recommendation",
        status: "succeeded",
        progressPct: 100,
        gpus: 16,
        startedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
        etaMin: 0,
        dataset: "interactions-30d",
      },
      {
        id: "tj4",
        modelName: "semantic-search",
        kind: "search",
        status: "failed",
        progressPct: 44,
        gpus: 4,
        startedAt: new Date(Date.now() - 18 * 3600000).toISOString(),
        etaMin: null,
        dataset: "catalog-embeddings-v8",
      },
    ],
    inferenceServers: [
      {
        id: "is1",
        name: "triton-recs-eu",
        models: "rec-v3",
        region: "eu-west-1",
        replicas: 6,
        status: "healthy",
        qps: 6800,
        gpuUtilPct: 74,
        runtime: "triton",
      },
      {
        id: "is2",
        name: "vllm-chat-global",
        models: "support-chatbot",
        region: "multi",
        replicas: 4,
        status: "scaling",
        qps: 420,
        gpuUtilPct: 88,
        runtime: "vllm",
      },
      {
        id: "is3",
        name: "torchserve-ocr",
        models: "receipt-ocr",
        region: "us-east-1",
        replicas: 3,
        status: "healthy",
        qps: 110,
        gpuUtilPct: 41,
        runtime: "torchserve",
      },
      {
        id: "is4",
        name: "search-embed-apac",
        models: "semantic-search",
        region: "ap-southeast-1",
        replicas: 5,
        status: "degraded",
        qps: 4200,
        gpuUtilPct: 92,
        runtime: "custom",
      },
    ],
    gpuNodes: [
      {
        id: "g1",
        hostname: "gpu-eu-01",
        region: "eu-west-1",
        gpuModel: "A100 80GB",
        gpuCount: 8,
        utilPct: 72,
        memUsedPct: 68,
        tempC: 64,
        status: "healthy",
      },
      {
        id: "g2",
        hostname: "gpu-eu-02",
        region: "eu-west-1",
        gpuModel: "A100 80GB",
        gpuCount: 8,
        utilPct: 81,
        memUsedPct: 77,
        tempC: 71,
        status: "healthy",
      },
      {
        id: "g3",
        hostname: "gpu-us-01",
        region: "us-east-1",
        gpuModel: "H100 80GB",
        gpuCount: 8,
        utilPct: 94,
        memUsedPct: 91,
        tempC: 82,
        status: "throttled",
      },
      {
        id: "g4",
        hostname: "gpu-apac-01",
        region: "ap-southeast-1",
        gpuModel: "A10G",
        gpuCount: 4,
        utilPct: 55,
        memUsedPct: 48,
        tempC: 58,
        status: "healthy",
      },
      {
        id: "g5",
        hostname: "gpu-eu-train-01",
        region: "eu-central-1",
        gpuModel: "H100 80GB",
        gpuCount: 16,
        utilPct: 88,
        memUsedPct: 84,
        tempC: 76,
        status: "healthy",
      },
    ],
  };
}

export async function fetchAiPlatformSnapshot(): Promise<AiPlatformSnapshot> {
  try {
    return await apiClient<AiPlatformSnapshot>(platformPath("/ai-platform"));
  } catch (err) {
    if (err instanceof ApiError || err instanceof TypeError) {
      await new Promise((r) => setTimeout(r, 200));
      return mockSnapshot();
    }
    throw err;
  }
}
