CREATE TABLE IF NOT EXISTS auto_audits (
  id UUID PRIMARY KEY, tenant_id UUID NOT NULL, scope TEXT NOT NULL,
  status TEXT NOT NULL, score DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL, completed_at TIMESTAMPTZ NULL
);
CREATE TABLE IF NOT EXISTS auto_weaknesses (
  id UUID PRIMARY KEY, tenant_id UUID NOT NULL, audit_id UUID NOT NULL,
  code TEXT NOT NULL, title TEXT NOT NULL, severity TEXT NOT NULL, status TEXT NOT NULL,
  resolution TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS auto_heals (
  id UUID PRIMARY KEY, tenant_id UUID NOT NULL, kind TEXT NOT NULL,
  target_ref TEXT NOT NULL, action TEXT NOT NULL, status TEXT NOT NULL,
  automated BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL,
  executed_at TIMESTAMPTZ NULL
);
CREATE TABLE IF NOT EXISTS auto_reviews (
  id UUID PRIMARY KEY, tenant_id UUID NOT NULL, kind TEXT NOT NULL,
  summary TEXT NOT NULL, debt_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  suggestions JSONB NOT NULL DEFAULT '[]', created_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS auto_evolution (
  id UUID PRIMARY KEY, tenant_id UUID NOT NULL, kind TEXT NOT NULL,
  title TEXT NOT NULL, priority INT NOT NULL DEFAULT 3, status TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS auto_releases (
  id UUID PRIMARY KEY, tenant_id UUID NOT NULL, version TEXT NOT NULL,
  strategy TEXT NOT NULL, score DOUBLE PRECISION NOT NULL, status TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS auto_governance (
  id UUID PRIMARY KEY, tenant_id UUID NOT NULL, domain TEXT NOT NULL,
  cadence TEXT NOT NULL, healthy BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS auto_assistants (
  id UUID PRIMARY KEY, tenant_id UUID NOT NULL, role TEXT NOT NULL,
  name TEXT NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS auto_teams (
  id UUID PRIMARY KEY, tenant_id UUID NOT NULL, kind TEXT NOT NULL,
  name TEXT NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS auto_dependencies (
  id UUID PRIMARY KEY, tenant_id UUID NOT NULL, from_service TEXT NOT NULL,
  to_service TEXT NOT NULL, relation TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS auto_genesis (
  id UUID PRIMARY KEY, tenant_id UUID NOT NULL, version TEXT NOT NULL, status TEXT NOT NULL,
  gates JSONB NOT NULL DEFAULT '{}', issued_at TIMESTAMPTZ NULL, created_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS auto_outbox (
  id UUID PRIMARY KEY, tenant_id UUID NOT NULL, aggregate_id UUID NOT NULL,
  topic TEXT NOT NULL, key TEXT NOT NULL, payload JSONB NOT NULL, status TEXT NOT NULL,
  attempts INT NOT NULL DEFAULT 0, last_error TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, published_at TIMESTAMPTZ NULL
);
