import { ALLOW_MOCK_FALLBACK } from "@/shared/config/platform";
import { apiClient, ApiError, platformPath } from "@/shared/api/client";
import type { InfraSnapshot } from "./types";

function hours(): string[] {
  return ["00", "04", "08", "12", "16", "20"];
}

function mockSnapshot(): InfraSnapshot {
  const h = hours();
  return {
    generatedAt: new Date().toISOString(),
    kpis: {
      clusters: 6,
      nodes: 248,
      deployments: 412,
      certsExpiring: 3,
      cdnHitPct: 94.2,
      storageUsedPct: 67,
    },
    cpuSeries: h.map((label, i) => ({
      label: `${label}:00`,
      value: 42 + i * 6 + (i % 2) * 4,
    })),
    clusters: [
      {
        id: "c1",
        name: "prod-eu-west",
        region: "eu-west-1",
        provider: "aws",
        version: "1.30.2",
        nodeCount: 64,
        status: "healthy",
        cpuPct: 58,
        memPct: 71,
      },
      {
        id: "c2",
        name: "prod-us-east",
        region: "us-east-1",
        provider: "aws",
        version: "1.30.2",
        nodeCount: 72,
        status: "healthy",
        cpuPct: 61,
        memPct: 68,
      },
      {
        id: "c3",
        name: "prod-apac",
        region: "ap-southeast-1",
        provider: "gcp",
        version: "1.29.8",
        nodeCount: 48,
        status: "degraded",
        cpuPct: 78,
        memPct: 82,
      },
      {
        id: "c4",
        name: "staging-global",
        region: "eu-central-1",
        provider: "aws",
        version: "1.30.2",
        nodeCount: 24,
        status: "healthy",
        cpuPct: 31,
        memPct: 44,
      },
      {
        id: "c5",
        name: "edge-cdn-control",
        region: "global",
        provider: "azure",
        version: "1.29.4",
        nodeCount: 18,
        status: "healthy",
        cpuPct: 40,
        memPct: 52,
      },
      {
        id: "c6",
        name: "dr-warm-eu",
        region: "eu-south-1",
        provider: "aws",
        version: "1.30.2",
        nodeCount: 22,
        status: "healthy",
        cpuPct: 12,
        memPct: 28,
      },
    ],
    servers: [
      {
        id: "s1",
        hostname: "eu-cp-01",
        clusterId: "c1",
        role: "control-plane",
        instanceType: "m6i.2xlarge",
        status: "healthy",
        cpuPct: 22,
        memPct: 48,
        az: "eu-west-1a",
      },
      {
        id: "s2",
        hostname: "eu-w-14",
        clusterId: "c1",
        role: "worker",
        instanceType: "c6i.4xlarge",
        status: "healthy",
        cpuPct: 64,
        memPct: 71,
        az: "eu-west-1b",
      },
      {
        id: "s3",
        hostname: "apac-w-07",
        clusterId: "c3",
        role: "worker",
        instanceType: "n2-standard-8",
        status: "degraded",
        cpuPct: 91,
        memPct: 88,
        az: "asia-southeast1-b",
      },
      {
        id: "s4",
        hostname: "us-edge-02",
        clusterId: "c2",
        role: "edge",
        instanceType: "c6gn.2xlarge",
        status: "healthy",
        cpuPct: 45,
        memPct: 55,
        az: "us-east-1c",
      },
      {
        id: "s5",
        hostname: "bastion-ops",
        clusterId: "c4",
        role: "bastion",
        instanceType: "t3.medium",
        status: "healthy",
        cpuPct: 8,
        memPct: 32,
        az: "eu-central-1a",
      },
    ],
    namespaces: [
      {
        id: "ns1",
        name: "platform",
        clusterId: "c1",
        pods: 86,
        status: "healthy",
        quotas: "cpu 80 / mem 160Gi",
      },
      {
        id: "ns2",
        name: "tenant-shared",
        clusterId: "c1",
        pods: 214,
        status: "healthy",
        quotas: "cpu 200 / mem 400Gi",
      },
      {
        id: "ns3",
        name: "observability",
        clusterId: "c2",
        pods: 42,
        status: "healthy",
        quotas: "cpu 40 / mem 80Gi",
      },
      {
        id: "ns4",
        name: "ai-inference",
        clusterId: "c3",
        pods: 28,
        status: "degraded",
        quotas: "gpu 16 / mem 256Gi",
      },
    ],
    deployments: [
      {
        id: "d1",
        name: "bff-admin",
        namespace: "platform",
        clusterId: "c1",
        replicas: 8,
        ready: 8,
        image: "nexora/bff-admin:2.14.1",
        status: "healthy",
      },
      {
        id: "d2",
        name: "identity-service",
        namespace: "platform",
        clusterId: "c1",
        replicas: 6,
        ready: 6,
        image: "nexora/identity:1.9.0",
        status: "healthy",
      },
      {
        id: "d3",
        name: "config-flags",
        namespace: "platform",
        clusterId: "c2",
        replicas: 4,
        ready: 4,
        image: "nexora/config:3.2.0",
        status: "healthy",
      },
      {
        id: "d4",
        name: "rec-inference",
        namespace: "ai-inference",
        clusterId: "c3",
        replicas: 4,
        ready: 3,
        image: "nexora/rec-model:0.8.4",
        status: "degraded",
      },
    ],
    services: [
      {
        id: "svc1",
        name: "bff-admin",
        namespace: "platform",
        type: "ClusterIP",
        clusterIp: "10.40.12.8",
        ports: "8084/TCP",
      },
      {
        id: "svc2",
        name: "identity",
        namespace: "platform",
        type: "ClusterIP",
        clusterIp: "10.40.12.19",
        ports: "8443/TCP",
      },
      {
        id: "svc3",
        name: "gateway-edge",
        namespace: "platform",
        type: "LoadBalancer",
        clusterIp: "10.40.1.5",
        ports: "443/TCP",
      },
    ],
    ingresses: [
      {
        id: "ing1",
        name: "platform-api",
        namespace: "platform",
        hosts: "platform.nexora.global",
        tls: true,
        className: "nginx",
        status: "healthy",
      },
      {
        id: "ing2",
        name: "super-admin",
        namespace: "platform",
        hosts: "super.nexora.global",
        tls: true,
        className: "nginx",
        status: "healthy",
      },
      {
        id: "ing3",
        name: "grafana",
        namespace: "observability",
        hosts: "obs.nexora.global",
        tls: true,
        className: "nginx",
        status: "healthy",
      },
    ],
    certificates: [
      {
        id: "cert1",
        domain: "*.nexora.global",
        issuer: "Let's Encrypt",
        expiresAt: new Date(Date.now() + 68 * 86400000).toISOString(),
        status: "valid",
        autoRenew: true,
      },
      {
        id: "cert2",
        domain: "platform.nexora.global",
        issuer: "DigiCert",
        expiresAt: new Date(Date.now() + 18 * 86400000).toISOString(),
        status: "expiring",
        autoRenew: true,
      },
      {
        id: "cert3",
        domain: "cdn.nexora.global",
        issuer: "Cloudflare",
        expiresAt: new Date(Date.now() + 120 * 86400000).toISOString(),
        status: "valid",
        autoRenew: true,
      },
      {
        id: "cert4",
        domain: "legacy-api.nexora.io",
        issuer: "Sectigo",
        expiresAt: new Date(Date.now() + 9 * 86400000).toISOString(),
        status: "expiring",
        autoRenew: false,
      },
    ],
    dnsRecords: [
      {
        id: "dns1",
        zone: "nexora.global",
        name: "platform",
        type: "A",
        value: "18.200.12.44",
        ttl: 300,
        proxied: true,
      },
      {
        id: "dns2",
        zone: "nexora.global",
        name: "super",
        type: "CNAME",
        value: "platform.nexora.global",
        ttl: 300,
        proxied: true,
      },
      {
        id: "dns3",
        zone: "nexora.global",
        name: "_acme-challenge",
        type: "TXT",
        value: "challenge-token-…",
        ttl: 60,
        proxied: false,
      },
      {
        id: "dns4",
        zone: "nexora.global",
        name: "cdn",
        type: "CNAME",
        value: "d111111.cloudfront.net",
        ttl: 600,
        proxied: false,
      },
    ],
    storage: [
      {
        id: "st1",
        name: "pg-prod-eu",
        type: "ebs",
        region: "eu-west-1",
        sizeGb: 4096,
        usedPct: 62,
        status: "healthy",
        encrypted: true,
      },
      {
        id: "st2",
        name: "object-media",
        type: "s3",
        region: "global",
        sizeGb: 120000,
        usedPct: 71,
        status: "healthy",
        encrypted: true,
      },
      {
        id: "st3",
        name: "clickhouse-apac",
        type: "pd",
        region: "ap-southeast-1",
        sizeGb: 8192,
        usedPct: 84,
        status: "degraded",
        encrypted: true,
      },
      {
        id: "st4",
        name: "nfs-shared-ml",
        type: "nfs",
        region: "us-east-1",
        sizeGb: 2048,
        usedPct: 45,
        status: "healthy",
        encrypted: false,
      },
    ],
    cdn: [
      {
        id: "cdn1",
        name: "assets-global",
        provider: "cloudfront",
        domain: "cdn.nexora.global",
        status: "healthy",
        cacheHitPct: 95.1,
        bandwidthGbps: 12.4,
        origins: 3,
      },
      {
        id: "cdn2",
        name: "api-edge",
        provider: "cloudflare",
        domain: "edge.nexora.global",
        status: "healthy",
        cacheHitPct: 88.6,
        bandwidthGbps: 8.2,
        origins: 6,
      },
      {
        id: "cdn3",
        name: "media-apac",
        provider: "fastly",
        domain: "media-apac.nexora.global",
        status: "degraded",
        cacheHitPct: 79.2,
        bandwidthGbps: 4.1,
        origins: 2,
      },
    ],
  };
}

export async function fetchInfraSnapshot(): Promise<InfraSnapshot> {
  try {
    return await apiClient<InfraSnapshot>(platformPath("/infra"));
  } catch (err) {
    if (!ALLOW_MOCK_FALLBACK) throw err;
    if (err instanceof ApiError || err instanceof TypeError) {
      await new Promise((r) => setTimeout(r, 200));
      return mockSnapshot();
    }
    throw err;
  }
}
