services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: nexora
      POSTGRES_PASSWORD: nexora
      POSTGRES_DB: cart
    ports:
      - "5438:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexora -d cart"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6385:6379"

  kafka:
    image: bitnamilegacy/kafka:3.7
    environment:
      KAFKA_CFG_NODE_ID: "0"
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9099
    ports:
      - "9099:9092"
    profiles: ["kafka"]

  cart-service:
    build: .
    ports:
      - "8087:8087"
    environment:
      HTTP_ADDR: ":8087"
      GRPC_ADDR: ":9097"
      # Leave DATABASE_URL empty for in-memory dev mode
      REDIS_URL: redis://redis:6379
      KAFKA_BROKERS: kafka:9092
      CORS_ALLOWED_ORIGINS: "*"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  pgdata:
