import { apiClient, ApiError, platformPath } from "@/shared/api/client";
import type { GatewaySnapshot } from "./types";

function mockSnapshot(): GatewaySnapshot {
  const h = ["00", "04", "08", "12", "16", "20"];
  return {
    generatedAt: new Date().toISOString(),
    kpis: {
      rps: 184200,
      p99Ms: 142,
      errorRatePct: 0.28,
      activeKeys: 1248,
      oauthClients: 86,
      discoveredServices: 142,
    },
    trafficSeries: h.map((label, i) => ({
      label: `${label}:00`,
      value: 92000 + i * 18000 + (i % 3) * 5000,
    })),
    errorSeries: h.map((label, i) => ({
      label: `${label}:00`,
      value: 0.12 + i * 0.04 + (i === 3 ? 0.2 : 0),
    })),
    usageByRoute: [
      { label: "/v1/orders", value: 42 },
      { label: "/v1/catalog", value: 28 },
      { label: "/v1/identity", value: 18 },
      { label: "/platform/*", value: 8 },
      { label: "other", value: 4 },
    ],
    config: {
      edgeRegion: "multi-region anycast",
      tlsMinVersion: "1.2",
      jwtIssuer: "https://id.nexora.global",
      requestTimeoutMs: 15000,
      bodyLimitMb: 8,
      corsMode: "allowlist",
      wafEnabled: true,
    },
    routes: [
      {
        id: "r1",
        path: "/v1/platform/*",
        methods: "GET,POST,PUT,PATCH",
        upstream: "bff-admin",
        version: "v1",
        auth: "oidc",
        rateLimitRpm: 6000,
        status: "active",
      },
      {
        id: "r2",
        path: "/v1/orders/*",
        methods: "GET,POST",
        upstream: "order-service",
        version: "v1",
        auth: "oauth",
        rateLimitRpm: 120000,
        status: "active",
      },
      {
        id: "r3",
        path: "/v2/catalog/*",
        methods: "GET",
        upstream: "catalog-service",
        version: "v2",
        auth: "api_key",
        rateLimitRpm: 60000,
        status: "canary",
      },
      {
        id: "r4",
        path: "/healthz",
        methods: "GET",
        upstream: "edge-local",
        version: "v1",
        auth: "public",
        rateLimitRpm: 10000,
        status: "active",
      },
    ],
    apiKeys: [
      {
        id: "k1",
        name: "partner-acme",
        prefix: "nx_live_ac…",
        tenantId: "t-acme",
        scopes: "orders:read catalog:read",
        rateLimitRpm: 5000,
        lastUsedAt: new Date(Date.now() - 120000).toISOString(),
        status: "active",
        expiresAt: null,
      },
      {
        id: "k2",
        name: "mobile-edge",
        prefix: "nx_live_mo…",
        tenantId: null,
        scopes: "public:read",
        rateLimitRpm: 200000,
        lastUsedAt: new Date(Date.now() - 5000).toISOString(),
        status: "active",
        expiresAt: null,
      },
      {
        id: "k3",
        name: "legacy-integrator",
        prefix: "nx_live_lg…",
        tenantId: "t-legacy",
        scopes: "orders:write",
        rateLimitRpm: 1000,
        lastUsedAt: new Date(Date.now() - 14 * 86400000).toISOString(),
        status: "expired",
        expiresAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      },
      {
        id: "k4",
        name: "revoked-test",
        prefix: "nx_test_rv…",
        tenantId: "t-test",
        scopes: "platform:read",
        rateLimitRpm: 100,
        lastUsedAt: null,
        status: "revoked",
        expiresAt: null,
      },
    ],
    oauthClients: [
      {
        id: "o1",
        clientId: "admin-web",
        name: "Admin Web",
        grantTypes: "authorization_code, refresh_token",
        redirectUris: "https://admin.nexora.global/cb",
        scopes: "openid profile admin",
        status: "active",
        createdAt: "2024-01-12T00:00:00Z",
      },
      {
        id: "o2",
        clientId: "super-admin-web",
        name: "Super Admin Web",
        grantTypes: "authorization_code, refresh_token",
        redirectUris: "https://super.nexora.global/cb",
        scopes: "openid profile platform",
        status: "active",
        createdAt: "2025-06-01T00:00:00Z",
      },
      {
        id: "o3",
        clientId: "partner-sdk",
        name: "Partner SDK",
        grantTypes: "client_credentials",
        redirectUris: "—",
        scopes: "api:partner",
        status: "active",
        createdAt: "2025-02-20T00:00:00Z",
      },
      {
        id: "o4",
        clientId: "legacy-spa",
        name: "Legacy SPA",
        grantTypes: "implicit",
        redirectUris: "https://legacy.nexora.io/cb",
        scopes: "openid",
        status: "disabled",
        createdAt: "2022-08-01T00:00:00Z",
      },
    ],
    rateLimits: [
      {
        id: "rl1",
        name: "global-default",
        scope: "global",
        target: "*",
        limitRpm: 500000,
        burst: 20000,
        status: "enforced",
      },
      {
        id: "rl2",
        name: "platform-namespace",
        scope: "route",
        target: "/v1/platform/*",
        limitRpm: 6000,
        burst: 200,
        status: "enforced",
      },
      {
        id: "rl3",
        name: "tenant-burst-shadow",
        scope: "tenant",
        target: "t-*",
        limitRpm: 50000,
        burst: 5000,
        status: "shadow",
      },
      {
        id: "rl4",
        name: "key-partner-acme",
        scope: "key",
        target: "k1",
        limitRpm: 5000,
        burst: 250,
        status: "enforced",
      },
    ],
    versions: [
      {
        id: "v1",
        version: "v1",
        status: "stable",
        trafficPct: 86,
        sunsetAt: null,
        routes: 128,
      },
      {
        id: "v2",
        version: "v2",
        status: "beta",
        trafficPct: 12,
        sunsetAt: null,
        routes: 34,
      },
      {
        id: "v0",
        version: "v0",
        status: "deprecated",
        trafficPct: 2,
        sunsetAt: new Date(Date.now() + 90 * 86400000).toISOString(),
        routes: 18,
      },
    ],
    discovery: [
      {
        id: "sd1",
        service: "bff-admin",
        instances: 8,
        healthy: 8,
        registry: "k8s",
        endpoint: "bff-admin.platform.svc",
        status: "healthy",
      },
      {
        id: "sd2",
        service: "order-service",
        instances: 24,
        healthy: 23,
        registry: "k8s",
        endpoint: "order.orders.svc",
        status: "degraded",
      },
      {
        id: "sd3",
        service: "identity-service",
        instances: 6,
        healthy: 6,
        registry: "consul",
        endpoint: "identity.service.consul",
        status: "healthy",
      },
      {
        id: "sd4",
        service: "catalog-service",
        instances: 12,
        healthy: 12,
        registry: "k8s",
        endpoint: "catalog.catalog.svc",
        status: "healthy",
      },
    ],
  };
}

export async function fetchGatewaySnapshot(): Promise<GatewaySnapshot> {
  try {
    return await apiClient<GatewaySnapshot>(platformPath("/gateway"));
  } catch (err) {
    if (err instanceof ApiError || err instanceof TypeError) {
      await new Promise((r) => setTimeout(r, 200));
      return mockSnapshot();
    }
    throw err;
  }
}
