apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nexora-apps
resources:
  - ../base/namespaces.yaml
  - ../base/networkpolicy.yaml
  - ../base/keda-order.yaml
  - ../base/backup-cronjob.yaml
  - ../base/chaos-cronjob.yaml
  - canary-analysis.yaml
images:
  - name: ghcr.io/nexora/platform-ops-service
    newTag: prod
