default_platform(:android)

platform :android do
  lane :internal do
    upload_to_play_store(track: "internal", aab: "build/app/outputs/bundle/release/app-release.aab", skip_upload_apk: true)
  end
  lane :production do
    upload_to_play_store(track: "production", aab: "build/app/outputs/bundle/release/app-release.aab", skip_upload_apk: true, rollout: "0.1")
  end
end
